### ISSUE TITLE
Allgemeine Error logging / MessageBox Funktion

### ISSUE THREAD

**Issue by ScholliYT** [ScholliYT/SpieleProgrammierung#6]
Evtl. sollte man so ne art Logger hinzufügen, der bei nem Error auch ne MessageBox für den User erstellt.

**Comment by rueno** [comment]
![unbenannt](https://user-images.githubusercontent.com/10176104/51426238-00b90980-1be8-11e9-897b-fe59766a780d.PNG)
Sowas in der Art?

**Comment by rueno** [comment]
Nicht sicher, ob man Neu Starten als Option mit Greenfoot so implementieren könnte, da ein Client vom Host abhängig ist und vice vera, aber so vom optischen her?

**Comment by ScholliYT** [comment]
Das ist doch schon ziemlich cool. Den unternen Teil könnte man sonst auch einfach weg lassen.

**Comment by rueno** [comment]
Jo, den würd ich entfernern, da keine Email-Biblio vorhanden. Dann werd ich das bei zeiten mal portieren.

**Comment by ScholliYT** [comment]
Closed by ff5a4d77f89ab4b13138eed05a20c880589aaf4f

**Comment by ScholliYT** [comment]
Close
